[project]
name = "tts_project"
version = "0.1.0"
description = "Sistema modular de síntesis de voz con múltiples backends"
authors = ["Zeta <zeta@example.com>"]
requires-python = ">=3.10"

[tool.pdm.dependencies]
pyttsx3 = ">=2.90"
requests = ">=2.31.0"
boto3 = ">=1.34.0"  # Amazon Polly
azure-cognitiveservices-speech = ">=1.34.0"  # Azure TTS

[tool.pdm.dev-dependencies]
pytest = "*"

[tool.tts]
motor = "pyttsx3"

[tool.tts.motores]
pyttsx3 = "src.tts.backends.pyttsx3:MotorPyttsx3"
azure = "src.tts.backends.azure:MotorAzure"
polly = "src.tts.backends.polly:MotorPolly"
festival = "src.tts.backends.festival:MotorFestival"

[tool.tts.config.pyttsx3]
voz = "spanish"

[tool.tts.config.azure]
region = "eastus"
key = "tu_clave_azure"
voz = "es-ES-AlvaroNeural"

[tool.tts.config.polly]
region = "us-east-1"
access_key = "tu_access_key"
secret_key = "tu_secret_key"
voz = "Lucia"

[tool.tts.config.festival]
voz = "es"  # o "spanish_mbrola" si tenés MBROLA instalado
ruta_binario = "/usr/bin/festival"
